# FROM node:16-alpine

# WORKDIR "/app"
 
# COPY ./package.json ./
# RUN npm install

# RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
# # COPY ./ ./

# CMD ["npm", "run", "start"]

# -------------------------------------------------------

FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]